// <auto-generated />
using System;
using Hotel_manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007144154_CreationOfSeedersForRoomV2")]
    partial class CreationOfSeedersForRoomV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hotel_manager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Hotel_manager.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identidication_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("Hotel_manager.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("availability");

                    b.Property<byte>("MaxOccupancyPersons")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("max_occupancy_persons");

                    b.Property<double>("PricePerNight")
                        .HasColumnType("double")
                        .HasColumnName("price_per_night");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room_number");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "102",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "103",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "104",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "105",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "106",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "107",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "108",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "109",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "110",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "201",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "202",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "203",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "204",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 15,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "205",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "206",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "207",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "208",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "209",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "210",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "301",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "302",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "303",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "304",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 25,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "305",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "306",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "307",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "308",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 29,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "309",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "310",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 31,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "401",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "402",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 33,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "403",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "404",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 35,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "405",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "406",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 37,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "407",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 38,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "408",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 39,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "409",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 40,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "410",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 41,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "501",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "502",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 43,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "503",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 44,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "504",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 45,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "505",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "506",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 47,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 150.0,
                            RoomNumber = "507",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 48,
                            Availability = true,
                            MaxOccupancyPersons = (byte)4,
                            PricePerNight = 200.0,
                            RoomNumber = "508",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 49,
                            Availability = true,
                            MaxOccupancyPersons = (byte)1,
                            PricePerNight = 50.0,
                            RoomNumber = "509",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            Availability = true,
                            MaxOccupancyPersons = (byte)2,
                            PricePerNight = 80.0,
                            RoomNumber = "510",
                            RoomTypeId = 2
                        });
                });

            modelBuilder.Entity("Hotel_manager.Models.Room_type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("room_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Una acogedora habitación básica con una cama individual, ideal para viajeros solos.",
                            Name = "Habitación Simple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ofrece flexibilidad con dos camas individuales o una cama doble, perfecta para parejas o amigos.",
                            Name = "Habitación Doble"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espaciosa y lujosa, con una cama king size y una sala de estar separada, ideal para quienes buscan confort y exclusividad.",
                            Name = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Diseñada para familias, con espacio adicional y varias camas para una estancia cómoda.",
                            Name = "Habitación Familiar"
                        });
                });

            modelBuilder.Entity("Hotel_manager.Models.Room", b =>
                {
                    b.HasOne("Hotel_manager.Models.Room_type", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });
#pragma warning restore 612, 618
        }
    }
}
